# Generated by Django 6.0.3 on 2026-03-31 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuidador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_responsavel', models.CharField(max_length=200, verbose_name='Nome do Responsável')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ da Empresa')),
                ('razao_social', models.CharField(blank=True, max_length=255, verbose_name='Razão Social')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=20, verbose_name='WhatsApp')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('logradouro', models.CharField(max_length=200, verbose_name='Endereço/Rua')),
                ('sabe_sonda', models.BooleanField(default=False)),
                ('sabe_banho_leito', models.BooleanField(default=False)),
                ('sabe_transferencia', models.BooleanField(default=False)),
                ('exp_alzheimer', models.BooleanField(default=False)),
                ('nota_prova', models.IntegerField(default=0)),
                ('status_mei', models.CharField(choices=[('Ativo', 'Ativo'), ('Irregular', 'Irregular'), ('Pendente', 'Pendente')], default='Pendente', max_length=15)),
                ('doc_mei', models.FileField(blank=True, null=True, upload_to='docs/mei/')),
                ('doc_antecedentes', models.FileField(blank=True, null=True, upload_to='docs/criminais/')),
                ('em_escala', models.BooleanField(default=False)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListaNegra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ Bloqueado')),
                ('motivo', models.TextField(verbose_name='Motivo do Banimento')),
                ('data_bloqueio', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Lista Negra',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Paciente')),
                ('data_nascimento', models.DateField()),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('bairro', models.CharField(blank=True, max_length=100)),
                ('usa_sonda', models.BooleanField(default=False)),
                ('requer_banho_leito', models.BooleanField(default=False)),
                ('particularidades_pad', models.TextField()),
                ('tipo_escala', models.CharField(choices=[('12x36', '12h x 36h'), ('24x24', '24h x 24h'), ('Folguista', 'Folguista')], max_length=20)),
                ('cuidadores_direcionados', models.ManyToManyField(blank=True, related_name='pacientes', to='cuidadores.cuidador')),
            ],
        ),
    ]
